<?php

namespace AppBundle\Repository;

/**
 * EvernoteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvernoteUserRepository extends \Doctrine\ORM\EntityRepository
{
}
