<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EvernoteUser;
use Doctrine\DBAL\Types\Type;

/**
 * EvernoteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvernoteUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return EvernoteUser[]
     */
    public function findActive()
    {
        $users = $this
            ->createQueryBuilder("u")
            ->select("u")
            ->where("u.tokenExpiresAt > :now")
            ->setParameter("now", new \DateTime(), Type::DATETIME)
            ->getQuery()
            ->getResult();

        return $users;
    }
}
